version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm ci

  build:
    commands:
      - echo "Ejecutando build de React..."
      - npm run build

post_build:
  commands:
    - echo "Subiendo archivos a S3..."
    - aws s3 sync build/ s3://ipdepotweb/ --delete
    - echo "Invalidando cache de CloudFront..."
    - aws cloudfront create-invalidation \
        --distribution-id E2LKSU7JQU3CJ \
        --paths "/*"

artifacts:
  base-directory: build
  files:
    - '**/*'
